name = "Create Sublime Quilt 1.19.2"
author = "caseykat"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d86dfe6d62c12eb4cd4ce0111412a5cca3393130b32d09e16fe0d887c423939b"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
