name = "Create Sublime Quilt 1.19.2"
author = "caseykat"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b148ace7dacf2c0f412c658319a795c4a774a74828d2174694cb7a72df0ee236"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
