name = "Create Sublime Quilt 1.19.2"
author = "caseykat"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5682f3a91d4c57eee1fbfed5672497282d559f3d57c5b9cf9ebf575a0d3c5bc1"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"

[options]
acceptable-game-versions = ["1.19.2"]
